export const SET_NAME='SET_NAME';
export const SET_PHONE='SET_PHONE';
export const SET_EMAIL='SET_EMAIL';
export const SET_COMPANY_NAME='SET_COMPANY_NAME';


export const SET_PICKUP_ADDRESS='SET_PICKUP_ADDRESS';
export const SET_PICKUP_PIN='SET_PICKUP_PIN';
export const SET_DESTINATION_ADDRESS='SET_DESTINATION_ADDRESS';
export const SET_DESTINATION_PIN='SET_DESTINATION_PIN';

export const SET_NUMBER_OF_UNITS='SET_NUMBER_OF_UNITS';
export const SET_WEIGHT_PER_UNIT='SET_WEIGHT_PER_UNIT';
export const SET_UNIT='SET_UNIT';
export const SET_HEIGHT='SET_HEIGHT';
export const SET_WIDTH='SET_WIDTH';
export const SET_LENGTH='SET_LENGTH';

export const SET_PICKUP_DATE='SET_PICKUP_DATE';
export const SET_DELIVERY_DATE='SET_DELIVERY_DATE';
export const SET_PICKUP_SLOT='SET_PICKUP_SLOT';
export const SET_ADDITIONAL_NOTE='SET_ADDITIONAL_NOTE';

export const RESET_STATE='RESET_STATE';




//Logged in

export const SET_LOGGED_NAME='SET_LOGGED_NAME';
export const SET_LOGGED_EMAIL='SET_LOGGED_EMAIL';
export const SET_LOGGED_PHONE='SET_LOGGED_PHONE';
export const SET_LOGGED_ADDRESS='SET_LOGGED_ADDRESS';
export const SET_LOGGED_COMPANY_NAME='SET_LOGGED_COMPANY_NAME';
export const RESET_LOGGED_STATE='RESET_LOGGED_STATE';
export const SET_LOGGED_STATE='SET_LOGGED_STATE';


